### ISSUE TITLE
导入ACT报错

### ISSUE THREAD

**Issue by jisico** [Bluefissure/Yayiya#3]
未能解析此远程名称：‘dalamudplugins-1253720819.cos.ap-nanjing.mycloud.com’

**Comment by jisico** [comment]
妈咪救一救，谢谢妈咪

**Comment by Bluefissure** [comment]
dns问题

**Comment by Bluefissure** [comment]
不知道你是从哪下载的，明明应该是 myqcloud.com
https://github.com/Bluefissure/Yayiya/blob/master/Yayiya/Definitions.cs#L16
建议重新下载

**Comment by jisico** [comment]
谢谢妈咪  地址是我手输输错了
换了谷歌dns 8.8.8.8好用了
感谢
